[build]
command = "rustup toolchain install stable --profile minimal && rustup default stable && rustup target add wasm32-unknown-unknown && cargo install --locked trunk --version 0.21.14 && trunk build --release"
publish = "dist"
